site_name: Tech With Billy
theme:
  name: material


# Project information
site_name: Tech With Billy
site_author: Billy Wang
site_description: Tech Playground with Billy


# Copyright
copyright: >-
  Copyright &copy; All rights reserved. 2023 <a href="https://www.linkedin.com/in/billy-wangrb/">Billy Wang</a>, Guangzhou Billio Tech. Co., Ltd. <br>
  <a href="">Home</a>


# extra_css:
#   - assets/stylesheets/extra.css

# extra_javascript:
#   - assets/javascripts/extra.js

# Configuration
theme:
  name: material
  # custom_dir: docs/overrides
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - navigation.indexes
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
   - content.tabs.link
  palette:
    primary: grey
    # accent: custom
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/BillyWangRB
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/in/billy-wangrb/

markdown_extensions:
  - tables
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      # options:
      #         custom_icons:
      #           - overrides/.icons
  - toc:
      permalink: ¶
      toc_depth: 3

plugins:
  - glightbox
  - search
  - tags:
      tags_file: tags.md
  - blog:
      post_url_format: "{slug}"
      authors_file: "{blog}/.authors.yml"
      blog_toc: true
      post_excerpt_separator: <!-- more -->
      categories_name: Categories
      categories_toc: true
      pagination: true
      pagination_per_page: 10
      draft: true
      archive: false

nav:
  - Home: index.md
  - Work:
    - blog/index.md
    # - Openterface:
    #   - Weekly Update 3: openterface/update-3.md
  # - About: about.md